version: "3.1"
services:
  admin-db:
    container_name: admin-db
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5434:5432"
    volumes:
      - desafio-risk-test-volume:/var/lib/postgresql
volumes:
  desafio-risk-test-volume:
    external: true